url: https://beebul.github.io/
baseurl: /agency-jekyll-theme

# Site settings
title: Oliver Janaway
email: your-email@domain.com
description: "Visual Merchandiser for Hire. Based in Adelaide, South Australia."

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/oj_visual_merch/
  - title: linkedin
    url: https://www.linkedin.com/in/oliver-janaway-37bb9b75/

# Postal address (add as many lines as necessary)
address:
  - line: Adelaide
  - line: SA 5045

# Build settings
markdown: kramdown
permalink: pretty